name: UpdateJson

# masterにpushされたら実行 
#on:
#  push:
#    branches:
#      - master

# 毎時0分に実行
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  UpdateJson:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r src/python/requirements.txt
      - name: Run Python
        run: python src/python/getWiki.py
      - name: Commit files
        run: |
          git config --local user.email "super.pylori6@gmail.com"
          git config --local user.name "super-pylori"
          git add .
          git commit -m "Add changes" -a
          git push origin master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
#      - name: Upgrade NPM
#        run: npm install -g npm@6.13.6
      - name: Install NPM packages
        run: npm ci
      - name: Build website
        run: npm run build --if-present
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          